# Generated by Django 4.1 on 2022-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='date',
            field=models.DateField(),
        ),
    ]
